content/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('courses/', views.CourseList.as_view(), name='course_list'),
    path('<slug:course_slug>/', views.CourseDetail.as_view(), name='course_detail'),
    path('courses/create-course/', views.CreateCourse.as_view(), name='create_course'),
    path('<slug:course_slug>/delete/', views.DeleteCourse.as_view(), name='delete_course'),
    path('<slug:course_slug>/edit/', views.EditCourse.as_view(), name='edit_course'),
    path('<slug:course_slug>/add-unit/', views.AddUnit.as_view(), name='add_unit'),
    path('<slug:course_slug>/<slug:unit_slug>/', views.UnitDetail.as_view(), name='unit_detail'),
    path('<slug:course_slug>/<slug:unit_slug>/edit/', views.EditUnit.as_view(), name='edit_unit'),
    path('<slug:course_slug>/<slug:unit_slug>/delete/', views.DeleteUnit.as_view(), name='delete_unit'),
    path('<slug:course_slug>/<slug:unit_slug>/add-topic/', views.AddTopic.as_view(), name='add_topic'),
    path('<slug:course_slug>/<slug:unit_slug>/<slug:topic_slug>/', views.TopicDetail.as_view(), name='topic_detail'),
    path('<slug:course_slug>/<slug:unit_slug>/<slug:topic_slug>/edit/', views.EditTopic.as_view(), name='edit_topic'),
    path('<slug:course_slug>/<slug:unit_slug>/<slug:topic_slug>/delete/', views.DeleteTopic.as_view(), name='delete_topic'),
    path('<slug:course_slug>/<slug:unit_slug>/<slug:topic_slug>/quiz/', views.Quiz.as_view(), name='quiz'),
]

kaizenkingdom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('learn/', include('content.urls'), name='content_urls'),
    path('profile/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
]

profiles/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='profile.html'), name='profile'),
    path('update/', views.profile_update, name='profile_update'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

ACCOUNT_TYPE = [('student', 'Student'), ('teacher', 'Teacher')]

class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    account_type = models.CharField(max_length=7, choices=ACCOUNT_TYPE, default='student')
    display_name = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return f"{self.display_name} @{self.user.username}"
    
    class Meta:
        verbose_name_plural = "Custom Users"
    
    def save(self, *args, **kwargs):
        if not self.display_name:
            self.display_name = self.user.username
        super().save(*args, **kwargs)

@receiver(post_save, sender=User)
def create_or_update_user(sender, instance, created, **kwargs):
    if created:
        CustomUser.objects.create(user=instance)
        instance.customuser.save()

profiles/forms.py
from django import forms
from .models import CustomUser

class ProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['display_name']

profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm


@login_required
def profile(request):
    # Your logic to retrieve and pass user profile data here
    return render(request, 'profile.html')


@login_required
def profile_update(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=user.customuser)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = ProfileForm(instance=user.customuser)
    return render(request, 'profile_update.html', {'form': form})

profiles/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container d-flex justify-content-center flex-column">
    <h2 class="mt-3 text-center">Profile Information</h2>
    <div class="d-flex justify-content-center flex-column mt-3">
        <div class="user-info-grid">
            <div class="label">Username: </div>
            <div class="value">{{ user.username }}</div>
            <div class="label">Display Name: </div>
            <div class="value">{{ user.customuser.display_name }}</div>
            <div class="label">Account Type: </div>
            <div class="value">{{ user.customuser.get_account_type_display }}</div>
        </div>
    </div>
    <div class="text-center mt-3">
        <a href="{% url 'profile_update' %}" class="btn btn-primary mt-3">Edit Profile</a>
    </div>
</div>
{% endblock %}

profiles/templates/profile_update.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1 class="text-center mt-3">Update Profile</h1>
        <form method="post" class="mt-4">
            {% csrf_token %}
            <div class="form-group d-flex flex-column mt-3">
                <label for="{{ form.display_name.id_for_label }}" class="h4 text-center">Display Name:</label>
                {{ form.display_name }}
            </div>
            <div class="mt-3 mb-3 text-center">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a href="{% url 'profile' %}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}